# Generated by Django 4.0.5 on 2022-06-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'ゲームタイトル',
                'verbose_name_plural': 'ゲームタイトル群',
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_twitter_link', models.URLField()),
            ],
            options={
                'verbose_name': 'プレイヤー',
                'verbose_name_plural': 'プレイヤー群',
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Player_Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lftApp.game')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lftApp.player')),
            ],
            options={
                'db_table': 'player_game_relation',
            },
        ),
        migrations.CreateModel(
            name='LFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lftApp.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lftApp.player')),
            ],
            options={
                'verbose_name': 'LFT',
                'verbose_name_plural': 'LFT群',
                'db_table': 'lft',
            },
        ),
    ]
